### PR TITLE
Move mocha view to test view container

### PR DESCRIPTION
**Pull request by sandy081**
Hi,

I am developer from VS Code and recently we added a new test view container. Refer to the release notes [here](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_23.md#contributions-to-the-activity-bar). 

I am going through the popular extensions in the market place those contribute test related custom views and moving those view to Test view container.

I would request to accept this PR and publish the extension with changes.

Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/maty21/mocha-sidebar/100)

### CODE REVIEW

**Comment by sandy081** [comment]
I see PR is already submitted https://github.com/maty21/mocha-sidebar/pull/97

So closing mine

**Comment by maty21** [comment]
Hi thanks for the PR.
 we currently considering to support both of the options with configuration to decide which is better for your usage I believe that in some cases the tests should be placed in the same view as the code explorer .
btw is a common convention in the popular IDEs .
I will be happy to here your thoughts about my opinion

**Comment by sandy081** [comment]
@maty21 Agreed. But at the end of the day it is an user choice. 

Regarding extension authors able to show their view in explorer or other viewlet, there is an open issue here - https://github.com/Microsoft/vscode/issues/48704.

I think `test` location should be the default location for test views and user can customise. May I know the scenarios that it should be in explorer view?

**Comment by maty21** [comment]
For example we have a feature that check if something break after file saving .

**Comment by maty21** [comment]
Decoration is for cases that you editing the tests and you want to make sure that the specific case is running ok
but the case I mentioned is a little bit different,  I'm thinking of a scenario that you edit your code. the specific code can be tested via various test cases. therefore we have a feature that allows the user to check his tests automatically after file saving or after key up with a timeout. 
I know that it's not a deal breaker but IMO is more convenient that way 

in the next couple of days will add this feature and in order to support the two views we will have to do something tricky until you will add the feature you mentioned  [Microsoft/vscode#48704.](Microsoft/vscode#48704)

**Comment by NearAutomata** [comment]
I'd like to join the discussion with some insights. Personally I am developing 80% of my time on my Macbook hence screen real estate is very important to me. Considering I have a ton of test cases the respective test view can be bloated at times. Since I work in a workspace with about 10 project folders and have the open editors view I surely do not have the space to fit the mocha view under the project explorer. On top that I assume a change in your code will not only affect a single test and most likely an entire group. It's not as if there is only one icon to track 😄

**Comment by maty21** [comment]
There's no direct interction , the main view when you writing code is the explorer  and therefore is more convenient to see them at the same view as I mentioned before that's the preferred view on every IDE that I used

**Comment by maty21** [comment]
For closing this issue I add this feature and also had a way via config to move back to the explorer mode 
That feature is available from version 0.18.0
Thanks again for your support

**Comment by maty21** [comment]
@sandy081 issue that I currently have is that my tests are rendered only when the user selects the test view and therefore lenses and decoration will not be shown until the test view will be rendered
is there any workaround or should I open issue for this case

**Comment by sandy081** [comment]
@maty21 

>> my tests are rendered only when the user selects the test view and therefore lenses and decoration will not be shown until the test view will be rendered

I do not think editor decorations and code lenses depend on test view rendering? They are two independent features. May be is your code not getting activated until the test view is open?

**Pull request closed without merging**
