### PR TITLE
fix: allow for relative paths to installed mocha for finding, running,…

### PR DESCRIPTION
**Pull request by townbully**
… and debugging tests

---
This change is [Reviewable](https://reviewable.io/reviews/maty21/mocha-sidebar/140)

### CODE REVIEW

**Comment by eramitmittal** [comment]
Please see pull-request #127 . Which solves exactly this problem. 
However it is still open and next steps are not clear to me.

**Comment by maty21** [comment]
Tks for your PR I'll try to merge it soon

**Comment by townbully** [comment]
Hey, great!

Awesome extension, by the way.  I've just needed to tweak a few things to
use it on projects I'm working on, particularly the path calculation for
mocha.  I also increased a timeout value for tests reporting back because I
have a large suite and it was giving up before they finished.

I ended up simplifying the path calculation for mocha a bit more because it
seemed like vscode update broke the logic for require maybe?  Not totally
sure, but I pushed a slightly different fix.

A couple other things I wanted to dig into was it seems I can't run my full
test suite with it (I have hundreds of tests) but can run individual
groups.  I also don't see real-time updating of tests running (spinning
circles) and wanted to see if I could figure out that.

-Jeff

**Comment by maty21** [comment]
Nice great to here contoribution are more than welcome if you need any help on understanding something just pm me . If you fixing/adding different things split it to different PRs so it will be easy to merge it 

Thanks a lot

**Pull request closed without merging**
