### PR TITLE
mocha.path option should be used to find the tests

### PR DESCRIPTION
**Pull request by eramitmittal**
mocha.path option should be treated as relative to the workspace root folder

---
This change is [Reviewable](https://reviewable.io/reviews/maty21/mocha-sidebar/127)

### CODE REVIEW

**Comment by maty21** [comment]
btw on which configuration you run sidebar for typescript there is an open issue about running mocha sidebar with typescript.  but I haven't looked at it yet

**Comment by eramitmittal** [comment]
Hi,
I am not aware about the mocha sidebar issue with typescript. I will try and have a look.
The problem I faced with my project setup is:
1. My project uses mocha version 5.2.0
2. Sidebar extension ships with mocha version 2.5.3
3. If I specify full path to local mocha installation using mocha.path option, sidebar extension loads the correct version
4. If I specify relative path, sidebar extension always loads the mocha version shipped with the extension
5. I want to specify relative path so that I can commit this in version control. My team members in this way will not be required to manually specify the full path as per their machine.

Regarding your concern that sometimes people want to use global mocha, I can modify the code to use path.isAbsolute to check if the configuration really is relative or an absolute path

**Comment by eramitmittal** [comment]
I have updated the code, please review

**Comment by eramitmittal** [comment]
hi, did you get a chance to review this (adoption of sidebar extension in my team is blocked on this issue, I hope you understand :))

**Comment by eramitmittal** [comment]
Hi, did you get a chance to review this?

**Comment by eramitmittal** [comment]
Yes, without this change I am not able to specify relative path to 'local' mocha installation. 
Ability to specify relative path is important so that the change can be committed to version control.
Otherwise I have to use 'absolute' path which is off-course different on different machines. Due to this each and every dev in my team will be required to manually specify the path which is undesirable.

My patch is just 'completing' the functionality. Since mocha.path already allows specification of absolute path it is only natural that it also supports relative path.

**Comment by eramitmittal** [comment]
Interestingly, documentation for mocha.path suggests that user can provide relative path. 
But it does not work.
My patch is solving this by treating a relative path (if specified) w.r.t. workspace root folder

**Comment by eramitmittal** [comment]
Hi @maty21 , Any update on this please?

**Comment by maty21** [comment]
I'll will try my best to solve it o know your PR is open for a pretty long
time and I hope to find the way for fixing it for the next couple of weeks

**Pull request merged**
